networks:
  agent_zero_network:
    driver: bridge

volumes:
  agent_zero_data:
    driver: local
  ollama_data:
    driver: local

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    networks:
      - agent_zero_network
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/data
    environment:
      - OLLAMA_MODEL_PATH=/data/models
  agent-zero:
    image: frdel/agent-zero-run:latest
    container_name: agent-zero
    restart: always
    networks:
      - agent_zero_network
    ports:
      - "50001:80"
    expose:
      - "22"
      - "9000-9009"
    volumes:
      - agent_zero_data:/data
    env_file:
      - .env
